import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// <h1>Sound Stash</h1>
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Sound Stash</title>
      </head>

      <body>
        <header>

        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
